schema_version = '1.0.0'

id = 'marble_quick_menu'
version = '2.0.0'
name = 'Marble Quick Menu'
tagline = 'A Blender addon that dynamically loads custom sub-scripts, toggles menu options, and includes built-in efficiency tools.'
maintainer = 'Marble810 <kzkt@foxmail.com>'
type = 'add-on'

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]